name: Merge

on:
  schedule:
    - cron: "0 0,3,6,9,12,15,18,21 * * *" # every 3 hours
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch --unshallow
          git pull origin main
          git push origin main
